=== Loumstar/Nobius/validation/schemas/question.json
{
"$schema": "http://json-schema.org/draft/2019-09/schema#",
    "title": "Schema for question.json file.",
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "master_statement": {"type": "string"},
        "media": {
            "type": "array",
            "items": {"type": "string"}
        },
        "icon_data": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer",
                    "enum": [1, 2, 3]
                },
                "par_time": {
                    "type": "array",
                    "minItems": 2,
                    "maxItems": 2,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",
                        "minimum": 0
                    }
                },
                "statement": {"type": "string"}
            },
            "required": [
                "difficulty",
                "par_time"
            ]
        },
        "parts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "statement": {"type": "string"},
                    "media": {
                        "type": "array",
                        "items": {"type": "string"}
                    },
                    "input_symbols": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "response": {"type": "object"},
                    "responses": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "object"}
                    },
                    "custom_response": {
                        "type": "object",
                        "properties": {
                            "layout": {"type": "string"},
                            "responses": {"type": ["array", "object"]}
                        }
                    },
                    "final_answer": {
                        "type": "object",
                        "properties": {
                            "text": {"type": "string"},
                            "equation": {"type": "string"},
                            "media": {
                                "type": "array",
                                "items": {"type": "string"}
                            }
                        }
                    },
                    "worked_solutions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string"},
                                "equation": {"type": "string"},
                                "media": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                },
                                "is_final_answer": {
                                    "type": "boolean",
                                    "const": true
                                }
                            }
                        }
                    },
                    "structured_tutorial": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "text": {"type": "string"},
                                "h5p_link": {"type": "string"},
                                "media": {
                                    "type": "array",
                                    "items": {"type": "string"}
                                },
                                "response": {"type": "object"},
                                "responses": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {"type": "object"}
                                },
                                "custom_response": {
                                    "type": "object",
                                    "properties": {
                                        "layout": {"type": "string"},
                                        "responses": {"type": ["array", "object"]}
                                    }
                                }
                            }
                        }
                    },
                    "pre_response_text": {"type": "string"},
                    "post_response_text": {"type": "string"}
                },
                "required": ["statement"],
                "allOf": [
                    {
                        "if": {"required": ["response"]},
                        "then": {"properties": {"responses": false}}
                    },
                    {
                        "if": {"required": ["responses"]},
                        "then": {"properties": {"response": false}}
                    }
                ]
            }
        },
        "uid": {"type": "string"},
        "algorithm": {"type": "string"}
    },
    "required": [
        "title",
        "parts",
        "uid"
    ]
}

=== Loumstar/Nobius/example/renders/renders/Drag on a Plate.json
{
    "title": "Drag on a Plate",
    "icon_data": {
        "difficulty": 2,
        "par_time": [
            15,
            20
        ],
        "statement": "This question requires only ME1 knowledge, and is a chance to refresh the technique of using control volumes. We will use this technique extensively throughout the year."
    },
    "master_statement": "A fluid with density \\(\\mathrm{\\rho = 800\\,kgm^{-3}}\\), flows at \\(\\mathrm{U_0 = 3\\,ms^{-1}}\\) over a flat plate of unit length and width. At the trailing edge the boundary-layer thickness is \\(\\mathrm{\\delta = 25\\,mm}\\). Assume the velocity at the trailing edge to be linear (as shown in Fig. 1), and the flow to be two-dimensional.",
    "media": [
        "Drag on a Plate Image.png"
    ],
    "parts": [
        {
            "statement": "Compute the mass flow rate across the top surface of the control volume (noted 'ab' in the image).",
            "response": {
                "mode": "Numeric",
                "showUnits": true,
                "grading": "toler_abs",
                "err": 0.1,
                "answer": {
                    "num": 30,
                    "units": "kg/s"
                },
                "comment": "",
                "name": "responseNan",
                "negStyle": "minus",
                "numStyle": "thousands scientific",
                "weighting": 1
            },
            "worked_solutions": [
                {
                    "media": [
                        "A4-Q3a.jpg"
                    ]
                },
                {
                    "is_final_answer": true
                }
            ],
            "final_answer": {
                "text": "30 kg/s"
            }
        },
        {
            "statement": "Determine the drag force on the plate.",
            "response": {
                "mode": "Numeric",
                "showUnits": true,
                "answer": {
                    "num": 30,
                    "units": "N"
                },
                "comment": "",
                "name": "responseNan",
                "negStyle": "minus",
                "numStyle": "thousands scientific",
                "grading": "exact_value",
                "weighting": 1
            },
            "worked_solutions": [
                {
                    "media": [
                        "A4-Q3b.jpg"
                    ]
                },
                {
                    "is_final_answer": true
                }
            ],
            "final_answer": {
                "text": "30 N"
            }
        }
    ],
    "uid": "320aef82-dc94-4051-956e-489c930fc247"
}

=== Loumstar/Nobius/example/renders/renders/Viscometer.json
{
    "title": "Viscometer",
    "icon_data": {
        "difficulty": 2,
        "par_time": [
            5,
            10
        ],
        "statement": "This question from ME1 has been selected here to showcase some of the features of Mobius."
    },
    "master_statement": "A long cylindrical rotor of length \\(L\\) and radius \\(R\\) rotates inside a cylindrical stator at a steady angular velocity \\(\\omega \\). The small gap between the rotor has a uniform radial width \\(d\\) and contains a fluid with uniform viscosity \\(\\mu \\), while the flow is incompressible and laminar.  Neglecting the curvature of the rotor and using cartesian coordinates, the differential equation describing the fluid motion is \\(\\frac{\\mathrm{d}^2u}{\\mathrm{d}y^2}=0\\).",
    "parts": [
        {
            "statement": "Find a simplified expression for the velocity profile, \\(u(y)\\), in terms of \\(\\omega\\), \\(R\\), \\(y\\), and \\(d\\). Define \\(y=0\\) at the radius of the rotor.",
            "response": {
                "mode": "Maple",
                "mapleAnswer": "omega*R*(1 - (y/d))",
                "comment": "",
                "name": "responseNan",
                "type": "maple",
                "plot": "",
                "allow2d": 0,
                "mathConversionMode": 0,
                "maple": "evalb(($ANSWER)-($RESPONSE)=0);",
                "weighting": 1,
                "custompreview": ""
            },
            "pre_response_text": "\\( u(y) = \\)",
            "worked_solutions": [
                {
                    "media": [
                        "A4-Q2a.png"
                    ]
                },
                {
                    "is_final_answer": true
                }
            ],
            "final_answer": {
                "text": "\\( \\omega R \\left(1 - \\frac{y}{d}\\right) \\)"
            }
        },
        {
            "statement": "Which of the following gives the correct expression for the magnitude of the power, \\(P\\), required to drive the rotor?",
            "response": {
                "mode": "Non Permuting Multiple Choice",
                "answer": 2,
                "choices": [
                    "<p>\\(P = \\frac{2\\pi L\\omega^2 R^3 \\mu}{d}\\)</p>",
                    "<p>\\(P = \\frac{2\\pi L\\omega R^3 \\mu}{d}\\)</p>",
                    "<p>\\(P = \\frac{\\pi L\\omega^2 d^3 \\mu}{R^2}\\)</p>",
                    "<p>\\(P = \\frac{2\\pi L\\omega^3 d^2 \\mu^2}{R^2}\\)</p>"
                ],
                "name": "responseNan",
                "weighting": 1,
                "comment": "",
                "display": "vertical"
            },
            "worked_solutions": [
                {
                    "media": [
                        "A4-Q2b.png"
                    ]
                },
                {
                    "is_final_answer": true
                }
            ],
            "final_answer": {
                "text": "\\(P = \\frac{2\\pi L\\omega^2 R^3 \\mu}{d}\\)"
            }
        }
    ],
    "uid": "5d292665-f506-4d44-8099-9b98d90777b9"
}

=== Loumstar/Nobius/example/Viscometer.json
{
   "title": "Viscometer",
   "icon_data": {
      "difficulty": 2,
      "par_time": [
         5,
         10
      ],
      "statement": "This question from ME1 has been selected here to showcase some of the features of Mobius."
   },
   "master_statement": "A long cylindrical rotor of length \\(L\\) and radius \\(R\\) rotates inside a cylindrical stator at a steady angular velocity \\(\\omega \\). The small gap between the rotor has a uniform radial width \\(d\\) and contains a fluid with uniform viscosity \\(\\mu \\), while the flow is incompressible and laminar. <br> Neglecting the curvature of the rotor and using cartesian coordinates, the differential equation describing the fluid motion is \\(\\frac{\\mathrm{d}^2u}{\\mathrm{d}y^2}=0\\).",
   "parts": [
      {
         "statement": "Find a simplified expression for the velocity profile, \\(u(y)\\), in terms of \\(\\omega\\), \\(R\\), \\(y\\), and \\(d\\). Define \\(y=0\\) at the radius of the rotor.",
         "pre_response_text": "\\( u(y) = \\)",
         "response": {
            "mode": "Maple",
            "mapleAnswer": "omega*R*(1 - (y/d))",
            "comment": ""
         },
         "input_symbols": [
            ["\\( \\omega \\)", "omega"],
            ["\\( R \\)", "R"],
            ["\\( y \\)", "y"],
            ["\\( d \\)", "d"]
         ],
         "final_answer": {
            "text": "\\( \\omega R \\left(1 - \\frac{y}{d}\\right) \\)"
         },
         "worked_solutions": [
            {
               "media": [
                  "A4-Q2a.png"
               ]
            },
            {
               "is_final_answer": true
            }
         ],
         "structured_tutorial": [
            {
               "h5p_link": "https://h5p.org/h5p/embed/981703"
            }
         ]
      },
      {
         "statement": "Which of the following gives the correct expression for the magnitude of the power, \\(P\\), required to drive the rotor?",
         "response": {
            "mode": "Non Permuting Multiple Choice",
            "answer": 2,
            "choices": [
               "<p>\\(P = \\frac{2\\pi L\\omega^2 R^3 \\mu}{d}\\)</p>",
               "<p>\\(P = \\frac{2\\pi L\\omega R^3 \\mu}{d}\\)</p>",
               "<p>\\(P = \\frac{\\pi L\\omega^2 d^3 \\mu}{R^2}\\)</p>",
               "<p>\\(P = \\frac{2\\pi L\\omega^3 d^2 \\mu^2}{R^2}\\)</p>"
            ],
            "name": "responseNan",
            "weighting": 1,
            "comment": ""
         },
         "final_answer": {
            "text": "\\(P = \\frac{2\\pi L\\omega^2 R^3 \\mu}{d}\\)"
         },
         "worked_solutions": [
            {
               "media": [
                  "A4-Q2b.png"
               ]
            },
            {
               "is_final_answer": true
            }
         ],
         "structured_tutorial": [
            {
               "h5p_link": "https://h5p.org/h5p/embed/981719"
            }
         ]
      }
   ],
   "uid": "5d292665-f506-4d44-8099-9b98d90777b9"
}
