=== Loumstar/Nobius/validation/schemas/sheet_info.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
        "title": "Schema for SheetInfo.json file.",
        "type": "object",
        "properties": {
            "name": {"type": "string"},
            "number": {"type": "integer"},
            "description": {"type": "string"},
            "questions": {
                "type": "array",
                "items": {"type": "string"},
                "minItems": 1
            },
            "uid": {"type": "string"}
        },
        "required": [
            "name",
            "number",
            "description",
            "questions",
            "uid"
        ]
    }

=== Loumstar/Nobius/xml_scraper/tests/questions/SheetInfo.json
{
    "number": 2,
    "name": "Experimental Sheet V2",
    "description": "Sheet to be bundled in lesson format",
    "uid": "a94acccf-a5d8-43ae-8cfb-e912d2bd2567",
    "questions": [
        "Hydraulic Scale",
        "Viscometer",
        "Drag on a Plate",
        "Small gravitational waves in shallow waters"
    ]
}

=== Loumstar/Nobius/example/renders/SheetInfo.json
{
    "number": 2,
    "name": "Experimental Sheet V2",
    "description": "Sheet to be bundled in lesson format",
    "uid": "b69cd704-444a-480f-ad4a-ff1de9a48eb1",
    "questions": [
        "Hydraulic Scale",
        "Viscometer",
        "Drag on a Plate",
        "Small gravitational waves in shallow waters",
        "Test"
    ]
}
